[template]

# The name of the template that will be used to render the application's configuration file
# Confd will look in `/etc/conf.d/templates` for these files by default
src = "midonet-api.xml.tmpl"

# The location to place the rendered configuration file
dest = "/usr/share/midonet-api/WEB-INF/web.xml"

# The etcd keys or directory to watch.  This is where the information to fill in
# the template will come from.
# prefix = "/services/midonet-api"
keys = [ "/" ]

# File ownership and mode information
owner = "root"
mode = "0664"

# These are the commands that will be used to check whether the rendered config is
# valid and to reload the actual service once the new config is in place
#check_cmd = "/usr/sbin/nginx -t"
reload_cmd = "/usr/share/tomcat/bin/catalina.sh stop && /usr/share/tomcat/bin/catalina.sh start"
